{
 "title": "Gatling Report",
 "description": "Gatling dashboard with parameters: granularity (1s, 5s, ...) and request filter",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "request",
    "label": "request",
    "query": "SHOW TAG VALUES WITH KEY = \"request\""
   },
   {
    "name": "writeInterval",
    "label": "gatling.data.graphite.writeInterval (sec)",
    "query": "1,5,10,30,60"
   },
   {
    "name": "g",
    "label": "granularity",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Indicators and Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indicators",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "t < 800 ms",
       "measurement": "gatling",
       "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE $timeFilter and \"mean\" <= 800 and \"status\" = 'ok' and \"request\" = 'allRequests'",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "800 ms < t < 1200 ms",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE $timeFilter and \"mean\" > 800 and \"mean\" <= 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "t > 1200 ms",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE $timeFilter and \"mean\" > 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE $timeFilter and \"status\" = 'ko' and \"request\" = 'allRequests'",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Statistics",
     "type": "table",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"simulation\" as \"1. simulation\", * FROM (  SELECT sum(\"count\") AS \"Total\" FROM \"gatling\" WHERE (\"status\" = 'all') AND $timeFilter GROUP BY \"simulation\", \"group1\", \"group2\", \"request\" ) GROUP BY \"1. simulation\" , \"group1\", \"group2\", \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"simulation\" as \"1. simulation\", * FROM ( SELECT sum(\"count\") AS \"OK\" FROM \"gatling\" WHERE (\"status\" = 'ok') AND $timeFilter GROUP BY \"simulation\", \"group1\", \"group2\", \"request\" ) GROUP BY \"1. simulation\" , \"group1\", \"group2\", \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "OK" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ok" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"simulation\" as \"1. simulation\", * FROM ( SELECT sum(\"count\") AS \"KO\" FROM \"gatling\" WHERE (\"status\" = 'ko') AND $timeFilter GROUP BY \"simulation\", \"group1\", \"group2\", \"request\") GROUP BY \"1. simulation\" , \"group1\", \"group2\", \"request\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "KO" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"simulation\" as \"1. simulation\", * FROM ( SELECT min(\"min\") AS \"Min\", percentile(\"percentiles50\", 50) AS \"50th pct\", percentile(\"percentiles75\", 75) AS \"75th pct\", percentile(\"percentiles95\", 95) AS \"95th pct\", percentile(\"percentiles99\", 99) AS \"99th pct\", max(\"max\") AS \"Max\", mean(\"mean\") AS \"Mean\", stddev(\"mean\") AS \"Std Dev\" FROM \"gatling\" WHERE (\"status\" = 'all') AND $timeFilter GROUP BY \"simulation\", \"group1\", \"group2\", \"request\" ) GROUP BY \"1. simulation\" , \"group1\", \"group2\", \"request\"",
       "select": [
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "Min" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "50th pct" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "75th pct" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "95th pct" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "99th pct" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "Std Dev" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Active Users (Scenarios) count per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Users along the Simulation",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ::  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Distribution (ok)",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "measurement": "gatling",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" }
       ]
      }
     ]
    },
    {
     "title": "Response Time Distribution (ko)",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "status" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" }
       ]
      }
     ]
    },
    {
     "title": "Response Time Percentiles over Time (OK)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ($col)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "50%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "95%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "99%" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "75%" ], "type": "alias" }
        ],
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "All users",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests per second (group by simulation),",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "reqps", "label": "Number of requests" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation (All)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'all' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / $writeInterval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_simulation (Active Users)",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of requests per second (group by simulation, status)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "reqps", "label": "Number of responses" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ($tag_status)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'all' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / $writeInterval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" }
       ]
      },
      {
       "alias": "$tag_simulation (Active Users)",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling.users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Script execution rate per second",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ::  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "done" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Script execution rate per minute",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ::  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "done" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Count: All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed scripts",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ::  $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling.users",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "done" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPS with filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction rate (PRS) for $request",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "[$tag_simulation] $tag_group1 / $tag_group2 $tag_request ($tag_status)",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" },
        { "params": [ "group2" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "group1" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / $writeInterval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latencies: Percentiles & Max (ok only)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation ($col)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "percentile 50" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "percentile 95" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "percentile 99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "percentile 75" ], "type": "alias" }
        ],
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors, Passes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors v Passes (count)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "pass ($tag_simulation)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "error ($tag_simulation)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ko' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Errors v Passes (per second)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "pass ($tag_simulation)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / $writeInterval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "error ($tag_simulation)",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ko' AND $timeFilter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / $writeInterval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=", "value": "allRequests" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Response time (group by request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individual Requests (95% Line)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_request",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "request" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE \"request\" <> 'allRequests' AND $timeFilter GROUP BY \"request\"",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Individual Request mean time (all statuses)",
     "type": "graph",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Individual Request mean time (ok/pass statuses)",
     "type": "graph",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ok" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Count: Error, Passed (group by request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individual Request count (ok/pass statuses)",
     "type": "graph",
     "description": "Чтобы оценить количество операций, которые были выполнены на каждый момент времени. Количество объектов, которые были созданы. Или количество записей в логе, об успешном выполнении операции, которые стоит ожидать.",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "Individual Request mean time (error/fail statuses)",
     "type": "graph",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Individual Request count (fail/error statuses)",
     "type": "graph",
     "description": "Чтобы оценить количество событий в логе ошибок, которые стоит ожидать. Чтобы попробовать скоррелировать графики ошибок по запросам с графиками текстов ошибок на стороне системы",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" }
       ]
      }
     ]
    }
   ]
  }
 ]
}